apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: ms-perfil-demografico
  labels:
    app: ms-perfil-demografico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-perfil-demografico
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-perfil-demografico
    spec:
      containers:
        - name: contenendor-ms-perfil-demografico
          image: IMAGE
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "350m"
          ports:
            - containerPort: 3060
            - containerPort: 4060
          env:
            - name: NODE_ENV
              value: "development"
            - name: AUTH_MS_HOST
              valueFrom:
                configMapKeyRef:
                  name: perfil-demografico-config-map
                  key: AUTH_MS_HOST
            - name: AUTH_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: perfil-demografico-config-map
                  key: AUTH_MS_PORT
            - name: MS_CATALOGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: perfil-demografico-config-map
                  key: MS_CATALOGO_HOST
            - name: MS_CATALOGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: perfil-demografico-config-map
                  key: MS_CATALOGO_PORT
            - name: USER_MS_HOST
              valueFrom:
                configMapKeyRef:
                  name: perfil-demografico-config-map
                  key: USER_MS_HOST
            - name: USER_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: perfil-demografico-config-map
                  key: USER_MS_PORT
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: perfil-demografico-secrets
                  key: POSTGRES_USER
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: perfil-demografico-secrets
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: perfil-demografico-secrets
                  key: POSTGRES_HOST
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: perfil-demografico-secrets
                  key: POSTGRES_PORT
                  optional: false
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: perfil-demografico-secrets
                  key: POSTGRES_DB
                  optional: false
          # Realizar pull siempre a la imagen
          imagePullPolicy: Always
      serviceAccountName: ksa-dev-sportapp
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: development
  name: sportapp-perfil-demografico-backendconfig
spec:
  timeoutSec: 65
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 3
    requestPath: /perfil-demografico/health
---
kind: Service
apiVersion: v1
metadata:
  namespace: development
  name: service-ms-perfil-demografico
  annotations:
    cloud.google.com/backend-config: '{"default": "sportapp-perfil-demografico-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: ms-perfil-demografico
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3060
---
kind: Service
apiVersion: v1
metadata:
  namespace: development
  name: service-ms-tcp-perfil-demografico
  annotations:
    cloud.google.com/backend-config: '{"default": "sportapp-perfil-demografico-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: ms-perfil-demografico
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4060